{"name": "Проверка ошибки, если авторизоваться под несуществующим пользователем", "status": "passed", "description": "Заполняем \"Логин\" и \"Пароль\" случайными данными. Проверяем: статус код  = 401Текст сообщения: \"email or password are incorrect\"", "steps": [{"name": "Заполняем \"Логин\" и \"Пароль\" случайными данными", "status": "passed", "start": 1703455739595, "stop": 1703455739595}], "start": 1703455739594, "stop": 1703455740006, "uuid": "f5e27654-5e1b-4b17-aff2-f58d576536cc", "historyId": "581f9c6e4ece797e6eba2da8f0247311", "testCaseId": "581f9c6e4ece797e6eba2da8f0247311", "fullName": "tests.test_login_user.TestLoginUser#test_login_and_password_user_false", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-588797DN"}, {"name": "thread", "value": "15472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}