{"name": "Проверка возникновения ошибки, при создании двух одинаковых пользователей", "status": "passed", "description": "Создаем пользователя. Используем переданные данные для нового запроса на создание пользователяПроверяем: статус код = 403Информацию об ошибочном создании пользователяТекст сообщения: \"User already exists\"", "steps": [{"name": "Создаем курьера. И запоминаем данные", "status": "passed", "start": 1705695580624, "stop": 1705695581191}], "start": 1705695580624, "stop": 1705695581625, "uuid": "8dd6ffd3-1497-4f45-b806-98bacb9a2111", "historyId": "3127ef2e90926239eaa4b1434d7187a2", "testCaseId": "3127ef2e90926239eaa4b1434d7187a2", "fullName": "tests.test_create_user.TestCreateUser#test_create_two_identical_user_false", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "LAPTOP-588797DN"}, {"name": "thread", "value": "6072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}