{"name": "Проверка ошибки, если авторизоваться под несуществующим пользователем", "status": "passed", "description": "Заполняем \"Логин\" и \"Пароль\" случайными данными. Проверяем: статус код  = 401Текст сообщения: \"email or password are incorrect\"", "steps": [{"name": "Заполняем \"Логин\" и \"Пароль\" случайными данными", "status": "passed", "start": 1705695590627, "stop": 1705695590627}], "start": 1705695590627, "stop": 1705695591133, "uuid": "045fd67a-a92b-4ea4-b7be-aefa5b580b20", "historyId": "581f9c6e4ece797e6eba2da8f0247311", "testCaseId": "581f9c6e4ece797e6eba2da8f0247311", "fullName": "tests.test_login_user.TestLoginUser#test_login_and_password_user_false", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-588797DN"}, {"name": "thread", "value": "6072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}